name: Deployment Exercise 1
on: push
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
            node-version: 18.16
      - name: Install PNPM 
        uses: pnpm/action-setup@v2
        with:
          version: 8.4
      - name: Lint
          run: pnpm run lint
      - name: Test
          run: pnpm run test
      - name: Build
          run: pnpm run build
      - name: Deploy
          run: echo "Deployment would go here!"