name: Run Project Tests
on: push
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      # Use Action to grab our code from the repo
      - name: Get Code
        uses: actions/checkout@v3
        # Technically we don't need this action because it's pre-installed on ubuntu-latest
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
            node-version: 18.16
      - name: Install PNPM 
        uses: pnpm/action-setup@v2
        with:
          version: 8.4
      - name: Install Dependencies
        # pnpm ci is safer then pnpm install it locks in packages
        run: pnpm ci
      - name: Run tests
        run: pnpm test

